name: coverity
on: [push, pull_request]

jobs:
  analyze:
    # if: github.repository == 'c9s/r3'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        ./autogen.sh
        ./configure --enable-check --enable-debug
    - uses: vapier/coverity-scan-action@v1
      with:
        project: r3
        email: bjorn.a.svensson@est.tech
        # email: yoanlin93+github@gmail.com
        token: ${{ secrets.COVERITY_TOKEN }}
